---
alias: Aurora Alert
id: aurora_alert
triggers:
  - trigger: numeric_state
    entity_id: sensor.aurora_aurora_visibility_visibility
    above: 1
actions:
  - action: notify.alexa_media_everywhere
    data:
      message: "Alert! The Aurora Borealis might be visible right now!"
      data:
        type: announce
        # method: all
  - action: notify.mobile_app_nothing_phone_2
    data:
      title: "Aurora Alert"
      message: "Alert! The Aurora Borealis might be visible right now!"
