alias: "Away"
id: away
triggers:
  - trigger: state
    entity_id: binary_sensor.home_occupied
    from: "on"
    to: "off"
    for:
      minutes: 5
conditions:
  - condition: not
    conditions:
      - condition: state
        entity_id:
          - input_select.kyle_status_dropdown
          - input_select.charlotte_status_dropdown
        state: "Sleeping"
        match: any
  - condition: state
    entity_id: binary_sensor.guest_mode
    state: "off"
actions:
  - action: script.all_off
