---
alias: "Home in the dark"
id: home_in_the_dark
triggers:
  - trigger: state
    entity_id: binary_sensor.home_occupied
    from: "off"
    to: "on"
conditions:
  - condition: state
    entity_id: sun.sun
    state: "below_horizon"
  - condition: time
    before: '22:00:00'
  - condition: not
    conditions:
      - condition: state
        entity_id:
          - sensor.kyle_status
          - sensor.charlotte_status
        state: "Sleeping"
        match: any
actions:
  - action: logbook.log
    data:
      name: EVENT
      message: "Home in the dark."
  - action: light.turn_on
    data:
      entity_id: light.cosy_lights
  - action: light.turn_on
    data:
      entity_id: light.outside_lights

  - delay:
      minutes: 5
  - action: light.turn_off
    data:
      entity_id: light.outside_lights
