---
template:
  - sensor:
      - name: "Battery status"
        unique_id: battery_status
        state: >
          {%- set power_draw = states('sensor.givtcp_fd2308f368_battery_power') | int(0) %}
          {%- if power_draw < 0 %}
            Charging
          {%- elif power_draw == 0 %}
            Balanced
          {%- elif power_draw > 0 %}
            Draining
          {%- else -%}
            Indeterminate
          {%- endif %}
        icon: >-
          {%- set power_draw = states('sensor.givtcp_fd2308f368_battery_power') | int(0) %}
          {%- if power_draw < 0 %}
            mdi:battery-charging
          {%- elif power_draw > 0 %}
            mdi:battery-minus
          {%- else -%}
            mdi:battery
          {%- endif %}

      - name: "ASHP Heating COP"
        unique_id: ashp_heating_cop
        state: >
          {%- set heat_generated_state = states('sensor.viewpoint_device_0_arotherm_plus_heat_generated_heating') %}
          {%- set consumed_electricity_state = states('sensor.viewpoint_device_0_arotherm_plus_consumed_electrical_energy_heating') %}
          {%- if heat_generated_state in ['unavailable', 'unknown'] or consumed_electricity_state in ['unavailable', 'unknown'] %}
            unavailable
          {%- elif consumed_electricity_state | float(0) == 0 %}
            unknown
          {%- else %}
            {{ heat_generated_state | float / consumed_electricity_state | float }}
          {%- endif %}

      - name: "ASHP Hot Water COP"
        unique_id: ashp_hot_water_cop
        state: >
          {%- set heat_generated_state = states('sensor.viewpoint_device_0_arotherm_plus_heat_generated_domestic_hot_water') %}
          {%- set consumed_electricity_state = states('sensor.viewpoint_device_0_arotherm_plus_consumed_electrical_energy_heating') %}
          {%- if heat_generated_state in ['unavailable', 'unknown'] or consumed_electricity_state in ['unavailable', 'unknown'] %}
            unavailable
          {%- elif consumed_electricity_state | float(0) == 0 %}
            unknown
          {%- else %}
            {{ heat_generated_state | float / consumed_electricity_state | float }}
          {%- endif %}

        # "{{ states('sensor.viewpoint_device_0_arotherm_plus_heat_generated_domestic_hot_water') | int / states('sensor.viewpoint_device_0_arotherm_plus_consumed_electrical_energy_domestic_hot_water') | int | float(default='NaN') }}"

automation:
  - alias: Boost hot water
    id: boost_hot_water
    trigger:
      - platform: numeric_state
        entity_id: sensor.givtcp_fd2308f368_export_power
        above: 500
        for:
          minutes: 10
    action:
      - service: switch.turn_on
        target:
          entity_id: switch.viewpoint_domestic_hot_water_0_boost
      - service: notify.mobile_app_nothing_phone_2
        data:
          title: "Hot water boost triggered"
          message: "Hot water boost triggered whilst exporting."
