---
mqtt:
  sensor:
    - name: flightradar_home
      state_topic: 'flightradar/viewpoint'
      # just an example atm
      value_template: "{{ value_json.id if value_json.lat == 55 else states('sensor.outdoor_temperature') }}"

automation:
  - alias: 'Flight entry notification - Home'
    id: flight_entry_notification_home
    triggers:
      - trigger: event
        event_type: opensky_entry
        event_data:
          sensor: opensky_home
    conditions:
      - condition: template
        value_template: "{{ trigger.event.data.altitude <= 10000 }}"
    actions:
      - action: persistent_notification.create
        data:
          title: "Overflight event"
          message: 'Flight {{ trigger.event.data.callsign }} is passing nearby at {{ trigger.event.data.altitude }} meters.

          https://flightaware.com/live/flight/{{ trigger.event.data.callsign }}'

  - alias: 'Flight entry notification - Uplawmoor'
    id: flight_entry_notification_uplawmoor
    triggers:
      - trigger: event
        event_type: opensky_entry
        event_data:
          sensor: opensky_uplawmoor
    actions:
      - action: persistent_notification.create
        data:
          title: "{{ trigger.event.data.callsign }} Overflight - Uplawmoor"
          message: 'Flight {{ trigger.event.data.callsign }} is passing near Uplawmoor at {{ trigger.event.data.altitude }} meters.

          https://flightaware.com/live/flight/{{ trigger.event.data.callsign }}'
